### ISSUE TITLE
Setup Performance Measuring Infrastructure

### ISSUE THREAD

**Issue by ericpts** [ericpts/FAST#1]
We need a way to measure the performance of our program, so that we know when we are doing better.

Easiest would be to adapt the performance measurement infrastructure from the homeworks.

**Comment by glebmak** [comment]
@ericpts I will be looking into this today & tomorrow

**Comment by ericpts** [comment]
Make sure to pull the latest code.

**Comment by glebmak** [comment]
We have it by now
