### ISSUE TITLE
Find a way to attach git commit of the code running to the Benchmark meta info

### ISSUE THREAD

**Issue by glebmk** [ericpts/FAST#19]
Would be very useful for reproducibility of the results.
Here are some ideas:
https://stackoverflow.com/questions/1704907/how-can-i-get-my-c-code-to-automatically-print-out-its-git-version-hash

**Comment by ericpts** [comment]
I think this approach with the `#define` is the most convenient, since it does not involve creating any additional files: https://stackoverflow.com/a/12368262/5606132.

**Comment by glebmk** [comment]
Yep, that is what I will be implementing

**Comment by glebmk** [comment]
Probably in the same way we could attach compilation flags.

**Comment by mpeychev** [comment]
Pls, don't spend too much time on that - I don't think this issue is a high priority and a hacky solution should suffice.

**Comment by glebmk** [comment]
https://github.com/ericpts/FAST/pull/23. Was pretty easy to do
