### ISSUE TITLE
Verify correctness

### ISSUE THREAD

**Issue by mpeychev** [ericpts/FAST#4]
As a follow up of #1 , we need infrastructure to verify the correctness of out code.

**Comment by ericpts** [comment]
This is already in place!
The HMM class is capable of generating Hidden Markov Models, and of sampling from them:
https://github.com/ericpts/FAST/blob/master/src/hmm.hpp

The main file already contains an example of fitting using BW and then testing that the results are close to the actual parameters:
https://github.com/ericpts/FAST/blob/master/src/main.cpp

**Comment by mpeychev** [comment]
Ah, okay. Such a boss. Thank you 🙏 🙇
